# Generated by Django 2.2.12 on 2020-05-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=8)),
                ('password', models.CharField(default='13390924945', max_length=13)),
                ('phone', models.CharField(default='13390924945', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=20)),
                ('introduction', models.CharField(default='', max_length=20)),
                ('upload_time', models.DateField(default='')),
                ('uploader', models.TextField(default='')),
                ('method', models.CharField(choices=[('m1', 'model1'), ('m2', 'model2'), ('m3', 'model3')], max_length=10)),
                ('alarm_times', models.IntegerField(default='')),
                ('alarm_date', models.DateField(default='')),
                ('alarm_action', models.IntegerField(choices=[(1, 'kick'), (2, 'daily')])),
                ('statement', models.IntegerField(choices=[(1, 'checked'), (2, 'unchecked')])),
            ],
        ),
    ]
