# Generated by Django 2.2.12 on 2020-05-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='alarm_action',
            field=models.IntegerField(choices=[(1, 'kick'), (2, 'daily')], default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='alarm_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='video',
            name='method',
            field=models.CharField(choices=[('m1', 'model1'), ('m2', 'model2'), ('m3', 'model3')], default='m1', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='statement',
            field=models.IntegerField(choices=[(1, 'checked'), (2, 'unchecked')], default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_time',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
